# Generated by Django 2.1.7 on 2019-02-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
